name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2, 8.3]

    name: Laravel Compatibility Tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: none

    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Create test database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

    - name: Test multitenant package
      run: |
        cd packages/kodikas/multitenant
        composer install --no-interaction
        if [ -f "vendor/bin/phpunit" ]; then
          vendor/bin/phpunit
        fi

  create-release:
    needs: tests
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    name: Create Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: 🏢 Kodikas Laravel Multitenant ${{ github.ref }}
        body: |
          ## 🚀 Nueva Release
          
          ### Características incluidas:
          - Core multitenant functionality
          - Advanced user management (8 tipos de usuario, 6 niveles de roles)
          - Access control system avanzado
          - Tenant management con suscripciones
          - User invitation system
          - Administrative features completas
          
          ### Compatibilidad:
          - PHP 8.2+
          - Laravel 12.x exclusivamente
          
          Ver CHANGELOG.md para detalles completos.
        draft: false
        prerelease: false

  deploy-packagist:
    needs: tests
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    name: Deploy to Packagist

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Validate composer.json
      run: |
        composer validate packages/kodikas/multitenant/composer.json

    - name: Notify Packagist
      run: |
        echo "Release ${{ github.ref }} is ready for Packagist"
        echo "Manual update may be required at https://packagist.org/packages/kodikas/laravel-multitenant"
