name: Laravel Compatibility

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3]
        laravel: [12.*]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: none

    - name: Install Laravel ${{ matrix.laravel }}
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
        composer update --prefer-stable --prefer-dist --no-interaction --optimize-autoloader

    - name: Copy environment file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Create database
      run: touch database/database.sqlite

    - name: Run migrations
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate --force

    - name: Run compatibility tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit --testsuite=Feature

    - name: Test multitenant package compatibility
      run: |
        cd packages/kodikas/multitenant
        if [ -f "composer.json" ]; then
          echo "Testing multitenant package with Laravel ${{ matrix.laravel }} and PHP ${{ matrix.php }}"
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction
          if [ -f "vendor/bin/phpunit" ]; then
            vendor/bin/phpunit
          fi
        fi

    - name: Validate package structure
      run: |
        echo "🏢 Validating multitenant package structure..."
        cd packages/kodikas/multitenant
        
        # Check required files exist
        test -f composer.json || { echo "❌ composer.json missing"; exit 1; }
        test -f README.md || { echo "❌ README.md missing"; exit 1; }
        test -d src || { echo "❌ src directory missing"; exit 1; }
        test -d tests || { echo "❌ tests directory missing"; exit 1; }
