name: Security Scan

on:
  schedule:
    - cron: '0 2 * * 1' # Ejecutar cada lunes a las 2 AM UTC
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-security-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-security-

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Run Composer Security Audit
      run: composer audit --format=json > security-audit.json
      continue-on-error: true

    - name: Run PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@1.1
      with:
        composer-lock: './composer.lock'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci

    - name: Run npm security audit
      run: npm audit --audit-level moderate --json > npm-audit.json
      continue-on-error: true

    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v2
      with:
        languages: php, javascript

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Upload security artifacts
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          security-audit.json
          npm-audit.json

    - name: Comment on PR if vulnerabilities found
      if: github.event_name == 'pull_request' && failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '⚠️ **Security vulnerabilities detected!** Please review the security scan results before merging.'
          })
