name: Security

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
  schedule:
    - cron: '0 2 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest
    name: Security Scan

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv

    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist --no-dev

    - name: Security audit
      run: composer audit

    - name: Check for hardcoded secrets
      run: |
        echo "Checking for potential secrets..."
        grep -r -i "password\s*=" --include="*.php" . || echo "No hardcoded passwords found"
        grep -r -i "api[_-]key" --include="*.php" . || echo "No API keys found"
